// Generated by CoffeeScript 1.7.1
var app, express, logfmt, path, port;

express = require('express');

logfmt = require('logfmt');

path = require('path');

app = express();

app.use(logfmt.requestLogger());

app.use(express["static"](path.join(__dirname, '../client')));

port = Number(process.env.PORT || 5000);

app.listen(port, function() {
  return console.log('Listening on ' + port);
});
