// Generated by CoffeeScript 1.7.1
var app, bodyParser, express, logfmt, path, pg, port, unicorn;

express = require('express');

logfmt = require('logfmt');

path = require('path');

bodyParser = require('body-parser');

pg = require('pg');

unicorn = {
  bootstrap: new (require('./components/bootstrap')),
  config: new (require('./components/config')),
  db: new (require('./components/db')),
  module: new (require('./components/module')),
  api: new (require('./components/api')),
  webserver: new (require('./components/webserver'))
};

app = express();

app.use(logfmt.requestLogger());

app.use(bodyParser());

app.use(express["static"](path.join(__dirname, '../client')));

app.post('/', function(req, res) {
  return console.log(req.body);
});

port = Number(process.env.PORT || 5000);

app.listen(port, function() {
  return console.log('Listening on ' + port);
});
