// Generated by CoffeeScript 1.7.1
var unicorn;

unicorn = {
  bootstrap: new (require('./components/bootstrap')),
  config: new (require('./components/config')),
  db: new (require('./components/db')),
  persist: new (require('./components/persist')),
  module: new (require('./components/module')),
  api: new (require('./components/api')),
  webserver: new (require('./components/webserver'))
};
