// Generated by CoffeeScript 1.7.1
var API, fs, path;

fs = require('fs');

path = require('path');

module.exports = API = (function() {
  API.prototype.api = {};

  function API() {
    var dir, file, name, _i, _len, _ref;
    console.log('Initializing API ...');
    dir = path.join(__dirname, '../api');
    _ref = fs.readdirSync(dir);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      file = _ref[_i];
      name = file.split('.')[0];
      this.api[name] = new (require(path.join(dir, file)));
    }
  }

  API.prototype.execute = function(request) {
    if (request.entity === 'contact') {
      return {
        status: 'contact'
      };
    }
    return {
      status: 'notok'
    };
  };

  return API;

})();
