// Generated by CoffeeScript 1.7.1
var API, fs, path;

fs = require('fs');

path = require('path');

module.exports = API = (function() {
  API.prototype.api = {};

  function API() {
    var dir, file, name, _i, _len, _ref;
    console.log('Initializing API ...');
    dir = path.join(__dirname, '../api');
    _ref = fs.readdirSync(dir);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      file = _ref[_i];
      name = file.split('.')[0];
      this.api[name] = new (require(path.join(dir, file)));
    }
  }

  API.prototype.execute = function(request) {
    var entity, method, result;
    entity = request.entity;
    method = request.method;
    if (this.api[entity] === void 0) {
      return {
        status: "error",
        error: "API '" + entity + "' not implemented."
      };
    }
    if (typeof this.api[entity][method] !== 'function') {
      return {
        status: "error",
        error: "API '" + entity + "' does not implement method: '" + method + "'"
      };
    }
    if ((result = this.api[entity].validate(request)) === true) {
      return this.api[entity][method](request);
    } else {
      result.status = "error";
      return result;
    }
  };

  return API;

})();
