// Generated by CoffeeScript 1.7.1
var API;

module.exports = API = (function() {
  function API() {
    console.log('Initializing API ...');
  }

  API.prototype.execute = function(request) {
    return {
      status: 'ok'
    };
  };

  return API;

})();
