// Generated by CoffeeScript 1.7.1
var Webserver, bodyParser, express, logfmt, path;

express = require('express');

logfmt = require('logfmt');

path = require('path');

bodyParser = require('body-parser');

module.exports = Webserver = (function() {
  function Webserver() {
    var app, port;
    console.log('Starting webserver ...');
    app = express();
    app.use(logfmt.requestLogger());
    app.use(bodyParser());
    app.use(express["static"](path.join(__dirname, '../client')));
    app.post('/', function(req, res) {
      return console.log(req.body);
    });
    port = Number(process.env.PORT || 5000);
    app.listen(port, function() {
      return console.log('Listening on ' + port);
    });
  }

  return Webserver;

})();
