// Generated by CoffeeScript 1.7.1
(function() {
  requirejs.config({
    baseUrl: 'libraries',
    paths: {
      unicorn: '/unicorn'
    }
  });
  return requirejs(['jquery', 'underscore', 'backbone', 'unicorn/auth'], function($, _, Backbone, Auth) {
    $('body').html('modules loaded');
    return new Auth;
  });
}).call(this);
