// Generated by CoffeeScript 1.7.1
var ContactAPI;

module.exports = ContactAPI = (function() {
  function ContactAPI() {
    console.log('test constructor');
  }

  ContactAPI.prototype["delete"] = function(request) {};

  ContactAPI.prototype.load = function(request) {
    return {
      status: 'ok'
    };
  };

  ContactAPI.prototype.save = function(request) {};

  ContactAPI.prototype.validate = function(request) {
    return true;
  };

  return ContactAPI;

})();
